using ModelConstructors, Nullables, SMC, Test, Distributed, Distributions
using Dates, DataFrames, OrderedCollections, FileIO, DataStructures, LinearAlgebra, SparseArrays
using StatsBase, Random, CSV, StateSpaceRoutines, HDF5, JLD2, MAT, Plots
import ModelConstructors: @test_matrix_approx_eq, @test_matrix_approx_eq_eps
@everywhere using DSGE, JLD2, Printf, LinearAlgebra, ModelConstructors, SMC
HETDSGEGOVDEBT = "../src/models/heterogeneous/het_dsge_gov_debt/reference"

my_tests = [
    # ── altpolicy ──────────────────────────────────────────────────────────────
    "altpolicy/ait",
    "altpolicy/alt_inflation",
    "altpolicy/altpolicy",
    "altpolicy/default_policy",
    "altpolicy/flexible_ait",
    "altpolicy/ngdp_target",
    "altpolicy/rw",
    "altpolicy/rw_zero_rate",
    "altpolicy/smooth_ait_gdp",
    "altpolicy/smooth_ait_gdp_alt",
    "altpolicy/taylor_rule",
    "altpolicy/taylor93",
    "altpolicy/taylor99",
    "altpolicy/zero_rate",
    "altpolicy/zlb_rule",

    # ── analysis ───────────────────────────────────────────────────────────────
    "analysis/compute_meansbands",
    "analysis/create_q4q4_mb",
    "analysis/df_to_table",
    "analysis/io",
    "analysis/meansbands",
    "analysis/meansbands_to_matrix",
    "analysis/moments",
    "analysis/util",

    # ── everything else (commented out) ───────────────────────────────────────
    # "abstractdsgemodel",
    # "abstractvarmodel",
    # "defaults",
    # "parameters",
    # "util",
    # "grids",
    # "statespace/statespace",

    # "data/fred_data",
    # "data/load_data",
    # "data/load_data_poolmodel",
    # "data/misc",
    # "data/manual_data_adjustments",
    # "data/reverse_transform",
    # "data/simulate_data",
    # "data/transformations",
    # "data/transform_data",
    # "data/util",

    # "solve/gensys",
    # "solve/gensys2",
    # "solve/gensys_uncertain_altpol",
    # "solve/gensys2_uncertain_altpol_test1",
    # "solve/gensys2_uncertain_altpol_test2",
    # "solve/klein",
    # "solve/solve",
    # "solve/solve_poolmodel",
    # "solve/solve_ct",
    # "solve/gensys_ct",
    # "solve/reduction",

    # "estimate/filter",
    # "estimate/filter_hank",
    # "estimate/filter_poolmodel",
    # "estimate/cat",
    # "estimate/eig",
    # "estimate/posterior",
    # "estimate/posterior_poolmodel",
    # "estimate/estimate",
    # "estimate/estimate_bma",
    # "estimate/hessian",
    # "estimate/hessizero",
    # "estimate/kalman",
    # "estimate/lbfgs",
    # "estimate/marginal_data_density",
    # "estimate/metropolis_hastings",
    # "estimate/regime_switching_mh",
    # "estimate/nearest_spd",
    # "estimate/nelder_mead",
    # "estimate/combined_optimizer",
    # "estimate/csminwel",
    # "estimate/optimize",
    # "estimate/simulated_annealing",
    # "estimate/resample",
    # "estimate/transform_transition_matrices",
    # "estimate/util",
    # "estimate/backwards_compatibility",
    # "estimate/poolmodel_tpf",
    # "estimate/var/dsgevar_likelihood",
    # "estimate/var/dsgevecm_likelihood",
    # "estimate/smc/helpers",
    # "estimate/smc/initialization",
    # "estimate/smc/mutation",
    # "estimate/smc/online",
    # "estimate/smc/particle",
    # "estimate/smc/resample",
    # "estimate/smc/smc",
    # "estimate/smc/util",
    # "estimate/smc/regime_switching_smc",
    # "estimate/smc/Brookings_test/regime_switching_brookings",
    # "estimate/smc/Brookings_test/util_brookings",

    # "forecast/drivers",
    # "forecast/smooth",
    # "forecast/forecast",
    # "forecast/shock_decompositions",
    # "forecast/impulse_responses",
    # "forecast/io",
    # "forecast/forecast_one",
    # "forecast/automatic_tempalt_zlb",
    # "forecast/forecast_regime_switching",
    # "forecast/time_varying_credibility",
    # "forecast/tvcred_parameterize",
    # "forecast/multiple_altpol_imperfect_awareness",
    # "forecast/m1002_ss62_forecast_test",
    # "forecast/util",
    # "forecast/var/impulse_responses",
    # "forecast/var/dsgevar/impulse_responses",
    # "forecast/var/dsgevecm/impulse_responses",
    # "forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses",
    # "forecast/wrappers_impulse_responses/observables_identified_dsge_impulse_responses",
    # "forecast/wrappers_impulse_responses/var_approx_dsge_impulse_responses",

    # "scenarios/scenario",
    # "scenarios/forecast",
    # "scenarios/switching",
    # "scenarios/drivers",

    # "decomp/decompose_forecast",
    # "decomp/decomposition_periods",
    # "decomp/io",

    # "packet/packet",

    # "plot/util",
    # "plot/plot",

    # "models/financial_frictions",
    # "models/representative/an_schorfheide/an_schorfheide",
    # "models/representative/smets_wouters/smets_wouters",
    # "models/representative/smets_wouters/augment_states",
    # "models/representative/smets_wouters/observables",
    # "models/representative/smets_wouters/subspecs",
    # "models/representative/smets_wouters_orig/smets_wouters_orig",
    # "models/representative/m990/m990",
    # "models/representative/m1002/m1002",
    # "models/representative/m1010/m1010",
    # "models/representative/m904/m904",
    # "models/representative/m805/m805",
    # "models/representative/rep_dsge_gov_debt/rep_dsge_gov_debt",
    # "models/poolmodel/poolmodel",
    # "models/var/dsgevar/dsgevar",
    # "models/var/dsgevar/subspecs",
    # "models/var/dsgevar/measurement_error",
    # "models/var/dsgevecm/dsgevecm",
    # "models/var/dsgevecm/subspecs",
    # "models/var/dsgevecm/measurement_error",
    # "models/var/util",
    # "models/heterogeneous/het_dsge_gov_debt/het_dsge_gov_debt",
    # "models/heterogeneous/het_dsge_gov_debt/het_dsge_gov_debt_reduce_ell",
    # "models/heterogeneous/het_dsge/het_dsge",
    # "models/heterogeneous/het_dsge_gov_debt/het_dsge_gov_debt",
    # "models/heterogeneous/krusell_smith/krusell_smith",
    # "models/heterogeneous/krusell_smith_ct/krusell_smith_ct",
    # "models/heterogeneous/bond_labor/bond_labor",
    # "models/heterogeneous/real_bond/real_bond",
    # "models/heterogeneous/real_bond_mkup/real_bond_mkup",
    # "models/heterogeneous/one_asset_hank/one_asset_hank",
    # "models/heterogeneous/one_asset_hank/interns",
]

for test in my_tests
    test_file = string("$test.jl")
    @printf " * %s\n" test_file
    include(test_file)
end
